"""Builds sample/products.xlsx (100 grocery items). Prices are made up."""
import openpyxl

ROWS = [
 # name_en, name_ta, unit, price, aliases
 ("Sugar","சர்க்கரை","KG",48,"sakkarai, chakkarai, cheeni"),
 ("Rice (Ponni)","பொன்னி அரிசி","KG",58,"arisi, ponni, rice"),
 ("Raw Rice","பச்சரிசி","KG",52,"pacharisi, pacha arisi"),
 ("Idli Rice","இட்லி அரிசி","KG",46,"idli arisi"),
 ("Basmati Rice","பாஸ்மதி அரிசி","KG",120,"basmathi"),
 ("Wheat Flour (Atta)","கோதுமை மாவு","KG",44,"atta, godhumai maavu, wheat"),
 ("Maida","மைதா","KG",42,"maida maavu"),
 ("Rava (Sooji)","ரவை","KG",46,"ravai, sooji, semolina"),
 ("Rice Flour","அரிசி மாவு","KG",50,"arisi maavu"),
 ("Besan (Gram Flour)","கடலை மாவு","KG",95,"kadalai maavu, besan"),
 ("Toor Dal","துவரம் பருப்பு","KG",150,"thuvaram paruppu, tur dal, arhar"),
 ("Urad Dal","உளுத்தம் பருப்பு","KG",130,"ulundhu, ulutham paruppu, urad"),
 ("Moong Dal","பாசிப் பருப்பு","KG",125,"pasi paruppu, mung dal"),
 ("Chana Dal","கடலைப் பருப்பு","KG",90,"kadalai paruppu"),
 ("Bengal Gram (Kondakadalai)","கொண்டைக்கடலை","KG",110,"kondakadalai, chickpea, channa"),
 ("Green Gram (Payaru)","பச்சை பயறு","KG",115,"payaru, whole moong"),
 ("Peanut","நிலக்கடலை","KG",140,"verkadalai, groundnut, kadalai"),
 ("Sunflower Oil 1L","சூரியகாந்தி எண்ணெய்","LTR",165,"oil, ennai, sunflower"),
 ("Gingelly Oil 500ml","நல்லெண்ணெய்","PCS",220,"nallennai, sesame oil"),
 ("Coconut Oil 500ml","தேங்காய் எண்ணெய்","PCS",160,"thengai ennai"),
 ("Groundnut Oil 1L","கடலை எண்ணெய்","LTR",210,"kadalai ennai"),
 ("Ghee 200g","நெய்","PCS",140,"nei, ghee"),
 ("Salt 1kg","உப்பு","PKT",22,"uppu, salt"),
 ("Tamarind","புளி","KG",180,"puli"),
 ("Jaggery","வெல்லம்","KG",70,"vellam"),
 ("Turmeric Powder 100g","மஞ்சள் தூள்","PKT",35,"manjal, manjal thool, haldi"),
 ("Chilli Powder 100g","மிளகாய் தூள்","PKT",40,"milagai thool, chili powder"),
 ("Coriander Powder 100g","மல்லி தூள்","PKT",32,"malli thool, dhania powder"),
 ("Sambar Powder 100g","சாம்பார் பொடி","PKT",45,"sambar podi"),
 ("Rasam Powder 100g","ரசம் பொடி","PKT",42,"rasam podi"),
 ("Garam Masala 50g","கரம் மசாலா","PKT",48,"masala"),
 ("Pepper","மிளகு","KG",750,"milagu"),
 ("Cumin (Jeera)","சீரகம்","KG",420,"seeragam, jeera"),
 ("Mustard","கடுகு","KG",110,"kadugu"),
 ("Fenugreek (Venthayam)","வெந்தயம்","KG",120,"venthayam, methi"),
 ("Dry Red Chilli","வர மிளகாய்","KG",260,"vara milagai, red chilli"),
 ("Coriander Seeds (Malli)","மல்லி","KG",150,"malli, dhania"),
 ("Cardamom 50g","ஏலக்காய்","PKT",150,"elakkai, elaichi"),
 ("Cloves 50g","கிராம்பு","PKT",90,"kirambu, laung"),
 ("Cinnamon 50g","பட்டை","PKT",60,"pattai, dalchini"),
 ("Tea Powder 250g","டீ தூள்","PKT",110,"tea, chai, theneer"),
 ("Coffee Powder 200g","காபி தூள்","PKT",130,"coffee, kaapi"),
 ("Milk 500ml","பால்","PKT",30,"paal, milk packet"),
 ("Curd 500g","தயிர்","PKT",32,"thayir, curd, yogurt"),
 ("Butter 100g","வெண்ணெய்","PKT",60,"vennai, butter"),
 ("Paneer 200g","பன்னீர்","PKT",90,"paneer"),
 ("Eggs (1)","முட்டை","PCS",7,"muttai, egg"),
 ("Bread","ரொட்டி","PKT",40,"bread, pav"),
 ("Biscuit (Marie)","பிஸ்கட்","PKT",20,"biscuit, marie"),
 ("Biscuit (Cream)","கிரீம் பிஸ்கட்","PKT",30,"cream biscuit"),
 ("Rusk","ரஸ்க்","PKT",35,"rusk"),
 ("Noodles (Maggi)","நூடுல்ஸ்","PKT",14,"maggi, noodles"),
 ("Vermicelli","சேமியா","PKT",25,"semiya, vermicelli"),
 ("Poha (Aval)","அவல்","KG",70,"aval, poha"),
 ("Sago (Javvarisi)","ஜவ்வரிசி","KG",90,"javvarisi, sabudana"),
 ("Oats 500g","ஓட்ஸ்","PKT",95,"oats"),
 ("Corn Flakes 250g","கார்ன் ஃபிளேக்ஸ்","PKT",85,"cornflakes"),
 ("Onion","வெங்காயம்","KG",35,"vengayam, onion, ullipaya"),
 ("Small Onion (Sambar)","சின்ன வெங்காயம்","KG",90,"chinna vengayam, shallots"),
 ("Tomato","தக்காளி","KG",30,"thakkali, tomato"),
 ("Potato","உருளைக்கிழங்கு","KG",40,"urulai, urulaikizhangu, aloo"),
 ("Carrot","கேரட்","KG",50,"carrot"),
 ("Beans","பீன்ஸ்","KG",60,"beans"),
 ("Brinjal","கத்திரிக்காய்","KG",45,"kathirikai, brinjal, eggplant"),
 ("Ladies Finger","வெண்டைக்காய்","KG",50,"vendakkai, okra, bhindi"),
 ("Garlic","பூண்டு","KG",220,"poondu, garlic"),
 ("Ginger","இஞ்சி","KG",120,"inji, ginger"),
 ("Green Chilli","பச்சை மிளகாய்","KG",60,"pachai milagai"),
 ("Coconut","தேங்காய்","PCS",28,"thengai, coconut"),
 ("Lemon","எலுமிச்சை","PCS",5,"elumichai, lemon, limbu"),
 ("Banana (Robusta)","வாழைப்பழம்","KG",45,"vazhaipazham, banana"),
 ("Apple","ஆப்பிள்","KG",180,"apple, sevu"),
 ("Orange","ஆரஞ்சு","KG",90,"orange"),
 ("Bath Soap (Lux)","லக்ஸ் சோப்பு","PCS",38,"lux, kulikum soap"),
 ("Bath Soap (Santoor)","சந்தூர் சோப்பு","PCS",36,"santoor"),
 ("Washing Soap Bar","துவை சோப்பு","PCS",20,"thuvai soap, washing soap"),
 ("Detergent Powder 1kg","சலவை தூள்","PKT",110,"surf, detergent, washing powder"),
 ("Dish Wash Liquid 500ml","பாத்திரம் கழுவும் திரவம்","PCS",95,"vim, dishwash"),
 ("Shampoo Sachet","ஷாம்பூ","PCS",2,"shampoo, sachet"),
 ("Toothpaste 100g","பற்பசை","PCS",65,"paste, toothpaste, colgate"),
 ("Toothbrush","பல் துலக்கி","PCS",25,"brush, toothbrush"),
 ("Hair Oil 100ml","தலை எண்ணெய்","PCS",55,"hair oil, thalai ennai"),
 ("Talcum Powder 100g","பவுடர்","PCS",70,"talc, talcum"),
 ("Phenyl 500ml","பீனால்","PCS",60,"phenyl, floor cleaner"),
 ("Toilet Cleaner 500ml","கழிப்பறை கிளீனர்","PCS",85,"harpic, toilet cleaner"),
 ("Candle (Pack)","மெழுகுவர்த்தி","PKT",20,"candle, mezhugu"),
 ("Matchbox","தீப்பெட்டி","PCS",2,"theepetti, match box"),
 ("Camphor","கற்பூரம்","PKT",15,"karpooram, camphor"),
 ("Agarbathi","ஊதுபத்தி","PKT",20,"udhubathi, incense, agarbatti"),
 ("Pen (Ball)","பேனா","PCS",10,"pen, pena"),
 ("Notebook","நோட்டு புத்தகம்","PCS",40,"notebook, note book"),
 ("Pencil","பென்சில்","PCS",5,"pencil"),
 ("Eraser","அழிப்பான்","PCS",3,"eraser, rubber"),
 ("Mineral Water 1L","தண்ணீர் பாட்டில்","PCS",20,"water, thanneer, water bottle"),
 ("Soft Drink 600ml","குளிர்பானம்","PCS",40,"cool drink, soft drink, cola"),
 ("Soda","சோடா","PCS",15,"soda"),
 ("Chips Packet","சிப்ஸ்","PKT",20,"chips, wafers"),
 ("Murukku 200g","முறுக்கு","PKT",40,"murukku"),
 ("Mixture 200g","மிக்சர்","PKT",45,"mixture"),
 ("Chocolate Bar","சாக்லேட்","PCS",10,"chocolate, choco"),
 ("Candy (Pack)","மிட்டாய்","PKT",10,"mittai, candy, toffee"),
 ("Pickle 200g","ஊறுகாய்","PCS",55,"oorugai, pickle, achar"),
 ("Papad","அப்பளம்","PKT",30,"appalam, papad"),
]

wb = openpyxl.Workbook()
ws = wb.active
ws.title = "Products"
ws.append(["code", "name_en", "name_ta", "unit", "price", "aliases"])
for i, (en, ta, unit, price, al) in enumerate(ROWS, 1):
    ws.append([f"P{i:03d}", en, ta, unit, price, al])
for col, w in zip("ABCDEF", (8, 28, 28, 7, 9, 44)):
    ws.column_dimensions[col].width = w
ws.freeze_panes = "A2"
wb.save("sample/products.xlsx")
print(len(ROWS), "products")
